[project]
name = "dotgroup-teste-tecnico"
version = "0.1.0"
description = "Aplicações do desafio técnico e avaliação prática para a empresa Dotgroup."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "python-dotenv==1.2.3",
    "openai==3.17.0",
    "fastapi==0.141.1",
    "pytest==9.1.1",
    "httpx==0.28.1",
    "slowapi==0.1.10",
    "uvicorn[standard]==0.53.0",
    "langchain==1.2.11",
    "langchain-openai==1.6.2",
    "langgraph==1.2.6",
    "langgraph-cli[inmem]==0.4.31",
    "faiss-cpu==1.15.1",
    "sentence-transformers==6.1.0",
]
